-- 股票列表-基础信息
CREATE TABLE IF NOT EXISTS aistockzml_tushare_stock_basic (
    `EXCHANGE` text COMMENT 'Exchange',
    `CN_SPELL` text COMMENT 'Cn Spell',
    `IS_HS` text COMMENT 'Is Hs',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `NAME` text COMMENT 'Name名称',
    `LIST_STATUS` text COMMENT 'List Status',
    `UPDATE_BY` text COMMENT 'Update By',
    `SYMBOL` text COMMENT 'Symbol',
    `FULLNAME` text COMMENT 'Fullname名称',
    `ENNAME` text COMMENT 'Enname名称',
    `ASSET_CLASS` text COMMENT 'Asset Class',
    `CURR_TYPE` text COMMENT 'Curr Type',
    `LIST_DATE` text COMMENT 'List Date',
    `ACT_TYPE` text COMMENT 'Act Type',
    `ACT_ENT_TYPE` text COMMENT 'Act Ent Type',
    `ID` bigint(20) COMMENT 'Id',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `INDUSTRY` text COMMENT 'Industry',
    `DELIST_DATE` text COMMENT 'Delist Date',
    `ACT_NAME` text COMMENT 'Act Name名称',
    `CREATE_TIME` text COMMENT 'Create Time',
    `AREA` text COMMENT 'Area',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票列表-基础信息';



-- 交易日历
CREATE TABLE IF NOT EXISTS aistockzml_tushare_trade_cal (
    `ID` bigint(20) COMMENT 'Id',
    `EXCHANGE` text COMMENT 'Exchange',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `CAL_DATE` text COMMENT 'Cal Date',
    `IS_OPEN` bigint(20) COMMENT 'Is Open',
    `PRETRADE_DATE` text COMMENT 'Pretrade Date',
    `NEXT_TRADE_DATE` text COMMENT 'Next Trade Date',
    `CREATE_TIME` text COMMENT 'Create Time',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易日历';



-- 资产负债表
CREATE TABLE IF NOT EXISTS aistockzml_tushare_balancesheet (
    `RR_REINS_LTHINS_LIAB` text COMMENT 'Rr Reins Lthins Liab',
    `PAYROLL_PAYABLE` decimal(20,4) COMMENT 'Payroll Payable',
    `OTH_NCL` text COMMENT 'Oth Ncl',
    `INDEM_PAYABLE` text COMMENT 'Indem Payable',
    `CREATE_TIME` text COMMENT 'Create Time',
    `PRODUC_BIO_ASSETS` text COMMENT 'Produc Bio Assets',
    `LT_AMOR_EXP` text COMMENT 'Lt Amor Exp',
    `OTH_ILLIQ_FIN_ASSETS` text COMMENT 'Oth Illiq Fin Assets',
    `DEFER_TAX_ASSETS` decimal(20,4) COMMENT 'Defer Tax Assets',
    `CLIENT_DEPOS` text COMMENT 'Client Depos',
    `SOLD_FOR_REPUR_FA` decimal(20,4) COMMENT 'Sold For Repur Fa',
    `OTH_PAYABLE` text COMMENT 'Oth Payable',
    `FAIR_VALUE_FIN_ASSETS` text COMMENT 'Fair Value Fin Assets',
    `LEASE_LIAB` decimal(20,4) COMMENT 'Lease Liab',
    `SYMBOL_FLAG` text COMMENT 'Symbol Flag',
    `LT_PAYABLE` text COMMENT 'Lt Payable',
    `CONTRACT_ASSETS` text COMMENT 'Contract Assets',
    `END_DATE` text COMMENT 'End Date',
    `AMOR_EXP` text COMMENT 'Amor Exp',
    `RR_REINS_UNE_PREM` text COMMENT 'Rr Reins Une Prem',
    `ADV_RECEIPTS` text COMMENT 'Adv Receipts',
    `POLICY_DIV_PAYABLE` text COMMENT 'Policy Div Payable',
    `LT_PAYROLL_PAYABLE` text COMMENT 'Lt Payroll Payable',
    `TIME_DEPOSITS` text COMMENT 'Time Deposits',
    `CASH_RESER_CB` decimal(20,4) COMMENT 'Cash Reser Cb',
    `INDEP_ACCT_ASSETS` text COMMENT 'Indep Acct Assets',
    `PH_INVEST` text COMMENT 'Ph Invest',
    `MINORITY_INT` text COMMENT 'Minority Int',
    `TOTAL_HLDR_EQY_EXC_MIN_INT` decimal(20,4) COMMENT 'Total Hldr Eqy Exc Min Int',
    `DERIV_ASSETS` decimal(20,4) COMMENT 'Deriv Assets',
    `RESER_LINS_LIAB` text COMMENT 'Reser Lins Liab',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `COMP_TYPE` text COMMENT 'Comp Type',
    `ACC_EXP` text COMMENT 'Acc Exp',
    `RSRV_INSUR_CONT` text COMMENT 'Rsrv Insur Cont',
    `INDEPT_ACC_LIAB` text COMMENT 'Indept Acc Liab',
    `USE_RIGHT_ASSETS` decimal(20,4) COMMENT 'Use Right Assets',
    `ST_BORR` text COMMENT 'St Borr',
    `BOND_PAYABLE` decimal(20,4) COMMENT 'Bond Payable',
    `DEPOS_RECEIVED` text COMMENT 'Depos Received',
    `CIP_TOTAL` text COMMENT 'Cip Total',
    `LOANTO_OTH_BANK_FI` decimal(20,4) COMMENT 'Loanto Oth Bank Fi',
    `PUR_RESALE_FA` decimal(20,4) COMMENT 'Pur Resale Fa',
    `DEPOS_IB_DEPOSITS` text COMMENT 'Depos Ib Deposits',
    `TOTAL_NCL` text COMMENT 'Total Ncl',
    `ACCOUNTS_RECEIV_BILL` text COMMENT 'Accounts Receiv Bill(数量)',
    `ID` bigint(20) COMMENT 'Id',
    `ANN_DATE` text COMMENT 'Ann Date',
    `INVEST_AS_RECEIV` text COMMENT 'Invest As Receiv',
    `CB_BORR` decimal(20,4) COMMENT 'Cb Borr',
    `DIV_PAYABLE` text COMMENT 'Div Payable',
    `SPECIFIC_PAYABLES` text COMMENT 'Specific Payables',
    `INVEST_LOSS_UNCONF` text COMMENT 'Invest Loss Unconf',
    `ACC_RECEIVABLE` text COMMENT 'Acc Receivable',
    `OTH_COMP_INCOME` decimal(20,4) COMMENT 'Oth Comp Income',
    `PAYABLES` text COMMENT 'Payables',
    `HFS_ASSETS` text COMMENT 'Hfs Assets',
    `UPDATE_BY` text COMMENT 'Update By',
    `ACTING_TRADING_SEC` text COMMENT 'Acting Trading Sec',
    `OTH_LIAB` decimal(20,4) COMMENT 'Oth Liab',
    `SETT_RSRV` text COMMENT 'Sett Rsrv',
    `REINSUR_RES_RECEIV` text COMMENT 'Reinsur Res Receiv',
    `LT_REC` text COMMENT 'Lt Rec',
    `LOAN_OTH_BANK` decimal(20,4) COMMENT 'Loan Oth Bank',
    `INT_RECEIV` text COMMENT 'Int Receiv',
    `FIXED_ASSETS_DISP` text COMMENT 'Fixed Assets Disp',
    `ACTING_UW_SEC` text COMMENT 'Acting Uw Sec',
    `DEPOS_OTH_BFI` decimal(20,4) COMMENT 'Depos Oth Bfi',
    `AGENCY_BUS_LIAB` text COMMENT 'Agency Bus Liab',
    `TREASURY_SHARE` text COMMENT 'Treasury Share',
    `OTH_RCV_TOTAL` text COMMENT 'Oth Rcv Total',
    `OTH_RECEIV` text COMMENT 'Oth Receiv',
    `DIV_RECEIV` text COMMENT 'Div Receiv',
    `INVEST_REAL_ESTATE` decimal(20,4) COMMENT 'Invest Real Estate',
    `ST_BONDS_PAYABLE` text COMMENT 'St Bonds Payable',
    `DEPOS` decimal(20,4) COMMENT 'Depos',
    `ORDIN_RISK_RESER` decimal(20,4) COMMENT 'Ordin Risk Reser',
    `GOODWILL` decimal(20,4) COMMENT 'Goodwill',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `REPORT_TYPE` text COMMENT 'Report Type',
    `TOTAL_SHARE` decimal(20,4) COMMENT 'Total Share',
    `PREMIUM_RECEIV` text COMMENT 'Premium Receiv',
    `OTH_CUR_ASSETS` text COMMENT 'Oth Cur Assets',
    `LT_EQT_INVEST` text COMMENT 'Lt Eqt Invest',
    `OTH_ASSETS` decimal(20,4) COMMENT 'Oth Assets',
    `OTH_NCA` text COMMENT 'Oth Nca',
    `REFUND_CAP_DEPOS` text COMMENT 'Refund Cap Depos',
    `TOTAL_CUR_ASSETS` text COMMENT 'Total Cur Assets',
    `PREC_METALS` decimal(20,4) COMMENT 'Prec Metals',
    `ACCT_PAYABLE` text COMMENT 'Acct Payable',
    `NON_CUR_LIAB_DUE_1Y` text COMMENT 'Non Cur Liab Due 1Y',
    `TOTAL_CUR_LIAB` text COMMENT 'Total Cur Liab',
    `OTH_EQT_TOOLS_P_SHR` decimal(20,4) COMMENT 'Oth Eqt Tools P Shr',
    `LENDING_FUNDS` text COMMENT 'Lending Funds',
    `HFS_SALES` text COMMENT 'Hfs Sales',
    `CAP_RESE` decimal(20,4) COMMENT 'Cap Rese',
    `FA_AVAIL_FOR_SALE` text COMMENT 'Fa Avail For Sale',
    `CIP` text COMMENT 'Cip',
    `INTAN_ASSETS` decimal(20,4) COMMENT 'Intan Assets',
    `RR_REINS_LINS_LIAB` text COMMENT 'Rr Reins Lins Liab',
    `COMM_PAYABLE` text COMMENT 'Comm Payable',
    `PAYABLE_TO_REINSURER` text COMMENT 'Payable To Reinsurer',
    `DEFER_TAX_LIAB` text COMMENT 'Defer Tax Liab',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `F_ANN_DATE` text COMMENT 'F Ann Date',
    `SURPLUS_RESE` decimal(20,4) COMMENT 'Surplus Rese',
    `REFUND_DEPOS` text COMMENT 'Refund Depos',
    `TRADING_FL` decimal(20,4) COMMENT 'Trading Fl',
    `PREM_RECEIV_ADVA` text COMMENT 'Prem Receiv Adva',
    `RESER_LTHINS_LIAB` text COMMENT 'Reser Lthins Liab',
    `PLEDGE_BORR` text COMMENT 'Pledge Borr',
    `TOTAL_ASSETS` decimal(20,4) COMMENT 'Total Assets',
    `INT_PAYABLE` text COMMENT 'Int Payable',
    `TOTAL_LIAB` decimal(20,4) COMMENT 'Total Liab',
    `TOTAL_LIAB_HLDR_EQY` decimal(20,4) COMMENT 'Total Liab Hldr Eqy',
    `ST_FIN_PAYABLE` text COMMENT 'St Fin Payable',
    `FIX_ASSETS_TOTAL` text COMMENT 'Fix Assets Total',
    `DEBT_INVEST` decimal(20,4) COMMENT 'Debt Invest',
    `CREATE_BY` text COMMENT 'Create By',
    `ACCOUNTS_RECEIV` text COMMENT 'Accounts Receiv(数量)',
    `PREPAYMENT` text COMMENT 'Prepayment',
    `RESER_OUTSTD_CLAIMS` text COMMENT 'Reser Outstd Claims',
    `LONG_PAY_TOTAL` text COMMENT 'Long Pay Total',
    `TRAD_ASSET` decimal(20,4) COMMENT 'Trad Asset',
    `RR_REINS_OUTSTD_CLA` text COMMENT 'Rr Reins Outstd Cla',
    `PH_PLEDGE_LOANS` text COMMENT 'Ph Pledge Loans',
    `NOTES_PAYABLE` text COMMENT 'Notes Payable',
    `ESTIMATED_LIAB` decimal(20,4) COMMENT 'Estimated Liab',
    `OTH_EQT_TOOLS` decimal(20,4) COMMENT 'Oth Eqt Tools',
    `OTH_DEBT_INVEST` decimal(20,4) COMMENT 'Oth Debt Invest',
    `OTH_EQ_INVEST` decimal(20,4) COMMENT 'Oth Eq Invest',
    `SPECIAL_RESE` text COMMENT 'Special Rese',
    `MONEY_CAP` text COMMENT 'Money Cap',
    `HTM_INVEST` text COMMENT 'Htm Invest',
    `DECR_IN_DISBUR` decimal(20,4) COMMENT 'Decr In Disbur',
    `DEPOS_IN_OTH_BFI` decimal(20,4) COMMENT 'Depos In Oth Bfi',
    `TRANSAC_SEAT_FEE` text COMMENT 'Transac Seat Fee',
    `DEFERRED_INC` text COMMENT 'Deferred Inc',
    `COST_FIN_ASSETS` text COMMENT 'Cost Fin Assets',
    `END_TYPE` text COMMENT 'End Type',
    `CONST_MATERIALS` text COMMENT 'Const Materials',
    `OTH_CUR_LIAB` text COMMENT 'Oth Cur Liab',
    `TOTAL_HLDR_EQY_INC_MIN_INT` decimal(20,4) COMMENT 'Total Hldr Eqy Inc Min Int',
    `OTH_EQ_PPBOND` decimal(20,4) COMMENT 'Oth Eq Ppbond',
    `RECEIV_FINANCING` text COMMENT 'Receiv Financing',
    `NOTES_RECEIV` text COMMENT 'Notes Receiv',
    `CLIENT_PROV` text COMMENT 'Client Prov',
    `INVENTORIES` text COMMENT 'Inventories',
    `R_AND_D` text COMMENT 'R And D',
    `FOREX_DIFFER` text COMMENT 'Forex Differ',
    `UNDISTR_PORFIT` decimal(20,4) COMMENT 'Undistr Porfit',
    `NCA_WITHIN_1Y` text COMMENT 'Nca Within 1Y',
    `FIX_ASSETS` decimal(20,4) COMMENT 'Fix Assets',
    `TOTAL_NCA` text COMMENT 'Total Nca',
    `ACCOUNTS_PAY` text COMMENT 'Accounts Pay(数量)',
    `LT_BORR` text COMMENT 'Lt Borr',
    `TAXES_PAYABLE` decimal(20,4) COMMENT 'Taxes Payable',
    `DERIV_LIAB` decimal(20,4) COMMENT 'Deriv Liab',
    `CONTRACT_LIAB` text COMMENT 'Contract Liab',
    `REINSUR_RECEIV` text COMMENT 'Reinsur Receiv',
    `DEFER_INC_NON_CUR_LIAB` text COMMENT 'Defer Inc Non Cur Liab',
    `RESER_UNE_PREM` text COMMENT 'Reser Une Prem',
    `OTH_PAY_TOTAL` text COMMENT 'Oth Pay Total',
    `OIL_AND_GAS_ASSETS` text COMMENT 'Oil And Gas Assets',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产负债表';



-- 沪深港通股票列表
CREATE TABLE IF NOT EXISTS aistockzml_tushare_stock_hsgt (
    `trade_date` text COMMENT '交易日期',
    `type` text COMMENT 'Type',
    `name` text COMMENT 'Name名称',
    `type_name` text COMMENT 'Type Name名称',
    `ts_code` text COMMENT '股票代码',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='沪深港通股票列表';



-- 上市公司基本信息
CREATE TABLE IF NOT EXISTS aistockzml_tushare_stock_company (
    `STATUS` text COMMENT 'Status',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `CHAIRMAN` text COMMENT 'Chairman',
    `SECRETARY` text COMMENT 'Secretary',
    `CREATE_TIME` text COMMENT 'Create Time',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `ID` bigint(20) COMMENT 'Id',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `EXCHANGE` text COMMENT 'Exchange',
    `COM_ID` text COMMENT 'Com Id',
    `SETUP_DATE` text COMMENT 'Setup Date',
    `PROVINCE` text COMMENT 'Province',
    `WEBSITE` text COMMENT 'Website',
    `EMAIL` text COMMENT 'Email',
    `MANAGER` text COMMENT 'Manager',
    `REG_CAPITAL` decimal(20,4) COMMENT 'Reg Capital',
    `COUNTRY` text COMMENT 'Country(数量)',
    `INTRODUCTION` text COMMENT 'Introduction',
    `OFFICE` text COMMENT 'Office',
    `BUSINESS_SCOPE` text COMMENT 'Business Scope',
    `EMPLOYEES` bigint(20) COMMENT 'Employees',
    `MAIN_BUSINESS` text COMMENT 'Main Business',
    `COM_NAME` text COMMENT 'Com Name名称',
    `CITY` text COMMENT 'City',
    `ANN_DATE` text COMMENT 'Ann Date',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='上市公司基本信息';



-- 利润表
CREATE TABLE IF NOT EXISTS aistockzml_tushare_income (
    `PREM_INCOME` text COMMENT 'Prem Income',
    `TOTAL_COGS` decimal(20,4) COMMENT 'Total Cogs',
    `OTH_INCOME` decimal(20,4) COMMENT 'Oth Income',
    `N_SEC_UW_INCOME` text COMMENT 'N Sec Uw Income',
    `OTH_B_INCOME` decimal(20,4) COMMENT 'Oth B Income',
    `REINS_COST_REFUND` text COMMENT 'Reins Cost Refund',
    `NON_OPER_EXP` decimal(20,4) COMMENT 'Non Oper Exp',
    `END_NET_PROFIT` text COMMENT 'End Net Profit',
    `CREATE_TIME` text COMMENT 'Create Time',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `BASIC_EPS` decimal(20,4) COMMENT 'Basic Eps',
    `PREM_EARNED` text COMMENT 'Prem Earned',
    `BIZ_TAX_SURCHG` decimal(20,4) COMMENT 'Biz Tax Surchg',
    `DIV_PAYT` text COMMENT 'Div Payt',
    `FOREX_GAIN` decimal(20,4) COMMENT 'Forex Gain',
    `COMPENS_PAYOUT` text COMMENT 'Compens Payout',
    `N_INCOME` decimal(20,4) COMMENT 'N Income',
    `RESER_INSUR_LIAB` text COMMENT 'Reser Insur Liab',
    `OPER_EXP` decimal(20,4) COMMENT 'Oper Exp',
    `COMPENS_PAYOUT_REFU` text COMMENT 'Compens Payout Refu',
    `INSUR_RESER_REFU` text COMMENT 'Insur Reser Refu',
    `TRANSFER_SURPLUS_RESE` text COMMENT 'Transfer Surplus Rese',
    `PRFSHARE_PAYABLE_DVD` text COMMENT 'Prfshare Payable Dvd',
    `TOTAL_OPCOST` text COMMENT 'Total Opcost',
    `CREATE_BY` text COMMENT 'Create By',
    `F_ANN_DATE` text COMMENT 'F Ann Date',
    `N_OTH_B_INCOME` decimal(20,4) COMMENT 'N Oth B Income',
    `FV_VALUE_CHG_GAIN` decimal(20,4) COMMENT 'Fv Value Chg Gain',
    `REINS_EXP` text COMMENT 'Reins Exp',
    `WITHDRA_LEGAL_SURPLUS` text COMMENT 'Withdra Legal Surplus',
    `CAPIT_COMSTOCK_DIV` text COMMENT 'Capit Comstock Div',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `EBIT` text COMMENT 'Ebit',
    `WORKERS_WELFARE` text COMMENT 'Workers Welfare',
    `OUT_PREM` text COMMENT 'Out Prem',
    `N_INCOME_ATTR_P` decimal(20,4) COMMENT 'N Income Attr P',
    `T_COMPR_INCOME` decimal(20,4) COMMENT 'T Compr Income',
    `COMSHARE_PAYABLE_DVD` text COMMENT 'Comshare Payable Dvd',
    `NET_AFTER_NR_LP_CORRECT` text COMMENT 'Net After Nr Lp Correct',
    `OTH_IMPAIR_LOSS_ASSETS` decimal(20,4) COMMENT 'Oth Impair Loss Assets',
    `IS_CALC` bigint(20) COMMENT 'Is Calc',
    `DILUTED_EPS` decimal(20,4) COMMENT 'Diluted Eps',
    `N_OTH_INCOME` decimal(20,4) COMMENT 'N Oth Income',
    `N_ASSET_MG_INCOME` text COMMENT 'N Asset Mg Income',
    `INVEST_INCOME` decimal(20,4) COMMENT 'Invest Income',
    `NON_OPER_INCOME` decimal(20,4) COMMENT 'Non Oper Income',
    `OTH_COMPR_INCOME` decimal(20,4) COMMENT 'Oth Compr Income',
    `DISTABLE_PROFIT` text COMMENT 'Distable Profit',
    `TRANSFER_HOUSING_IMPREST` text COMMENT 'Transfer Housing Imprest',
    `REVENUE` decimal(20,4) COMMENT 'Revenue',
    `PREM_REFUND` text COMMENT 'Prem Refund',
    `NCA_DISPLOSS` text COMMENT 'Nca Disploss',
    `INCOME_TAX` decimal(20,4) COMMENT 'Income Tax',
    `EBITDA` text COMMENT 'Ebitda',
    `WITHDRA_BIZ_DEVFUND` text COMMENT 'Withdra Biz Devfund',
    `DISTR_PROFIT_SHRHDER` text COMMENT 'Distr Profit Shrhder',
    `CONTINUED_NET_PROFIT` decimal(20,4) COMMENT 'Continued Net Profit',
    `REPORT_TYPE` text COMMENT 'Report Type',
    `N_SEC_TB_INCOME` text COMMENT 'N Sec Tb Income',
    `SELL_EXP` text COMMENT 'Sell Exp',
    `FIN_EXP` text COMMENT 'Fin Exp',
    `OTHER_BUS_COST` text COMMENT 'Other Bus Cost',
    `OPERATE_PROFIT` decimal(20,4) COMMENT 'Operate Profit(比率)',
    `TOTAL_PROFIT` decimal(20,4) COMMENT 'Total Profit',
    `TRANSFER_OTH` text COMMENT 'Transfer Oth',
    `ANN_DATE` text COMMENT 'Ann Date',
    `END_DATE` text COMMENT 'End Date',
    `TOTAL_REVENUE` decimal(20,4) COMMENT 'Total Revenue',
    `UNE_PREM_RESER` text COMMENT 'Une Prem Reser',
    `OPER_COST` text COMMENT 'Oper Cost',
    `INT_EXP` decimal(20,4) COMMENT 'Int Exp',
    `FIN_EXP_INT_INC` text COMMENT 'Fin Exp Int Inc',
    `ADJ_LOSSGAIN` text COMMENT 'Adj Lossgain',
    `ID` bigint(20) COMMENT 'Id',
    `REINS_INCOME` text COMMENT 'Reins Income',
    `ADMIN_EXP` decimal(20,4) COMMENT 'Admin Exp',
    `ASSETS_IMPAIR_LOSS` text COMMENT 'Assets Impair Loss',
    `MINORITY_GAIN` text COMMENT 'Minority Gain',
    `COMPR_INC_ATTR_M_S` text COMMENT 'Compr Inc Attr M S',
    `RD_EXP` text COMMENT 'Rd Exp',
    `WITHDRA_LEGAL_PUBFUND` text COMMENT 'Withdra Legal Pubfund',
    `COMPR_INC_ATTR_P` decimal(20,4) COMMENT 'Compr Inc Attr P',
    `INSURANCE_EXP` text COMMENT 'Insurance Exp',
    `WITHDRA_OTH_ERSU` text COMMENT 'Withdra Oth Ersu',
    `CREDIT_IMPA_LOSS` decimal(20,4) COMMENT 'Credit Impa Loss',
    `AMODCOST_FIN_ASSETS` decimal(20,4) COMMENT 'Amodcost Fin Assets',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `UPDATE_BY` text COMMENT 'Update By',
    `ASS_INVEST_INCOME` text COMMENT 'Ass Invest Income',
    `COMM_EXP` decimal(20,4) COMMENT 'Comm Exp',
    `UNDIST_PROFIT` text COMMENT 'Undist Profit',
    `FIN_EXP_INT_EXP` text COMMENT 'Fin Exp Int Exp',
    `ASSET_DISP_INCOME` decimal(20,4) COMMENT 'Asset Disp Income',
    `NET_EXPO_HEDGING_BENEFITS` text COMMENT 'Net Expo Hedging Benefits',
    `SYMBOL_FLAG` text COMMENT 'Symbol Flag',
    `END_TYPE` text COMMENT 'End Type',
    `COMM_INCOME` decimal(20,4) COMMENT 'Comm Income',
    `WITHDRA_RESE_FUND` text COMMENT 'Withdra Rese Fund',
    `COMP_TYPE` text COMMENT 'Comp Type',
    `INT_INCOME` decimal(20,4) COMMENT 'Int Income',
    `N_COMMIS_INCOME` decimal(20,4) COMMENT 'N Commis Income',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='利润表';



-- 现金流量表
CREATE TABLE IF NOT EXISTS aistockzml_tushare_cashflow (
    `END_TYPE` text COMMENT 'End Type',
    `STOT_CASH_IN_FNC_ACT` decimal(20,4) COMMENT 'Stot Cash In Fnc Act',
    `CREDIT_IMPA_LOSS` text COMMENT 'Credit Impa Loss',
    `N_INCR_DISP_FAAS` text COMMENT 'N Incr Disp Faas',
    `OTH_RECP_RAL_INV_ACT` text COMMENT 'Oth Recp Ral Inv Act',
    `N_DISP_SUBS_OTH_BIZ` text COMMENT 'N Disp Subs Oth Biz',
    `INCL_CASH_REC_SAIMS` text COMMENT 'Incl Cash Rec Saims',
    `UNCON_INVEST_LOSS` text COMMENT 'Uncon Invest Loss',
    `DEPR_FA_COGA_DPBA` text COMMENT 'Depr Fa Coga Dpba',
    `BEG_BAL_CASH_EQU` text COMMENT 'Beg Bal Cash Equ',
    `COMP_TYPE` text COMMENT 'Comp Type',
    `C_FR_SALE_SG` text COMMENT 'C Fr Sale Sg',
    `N_INCR_PLEDGE_LOAN` text COMMENT 'N Incr Pledge Loan',
    `C_RECP_BORROW` text COMMENT 'C Recp Borrow',
    `N_REINSUR_PREM` text COMMENT 'N Reinsur Prem',
    `N_CAP_INCR_REPUR` text COMMENT 'N Cap Incr Repur',
    `C_RECP_RETURN_INVEST` decimal(20,4) COMMENT 'C Recp Return Invest',
    `N_RECP_DISP_FIOLTA` decimal(20,4) COMMENT 'N Recp Disp Fiolta',
    `C_PREPAY_AMT_BORR` text COMMENT 'C Prepay Amt Borr(金额)',
    `EFF_FX_FLU_CASH` decimal(20,4) COMMENT 'Eff Fx Flu Cash',
    `C_RECP_CAP_CONTRIB` text COMMENT 'C Recp Cap Contrib',
    `LOSS_SCR_FA` text COMMENT 'Loss Scr Fa',
    `RECP_TAX_RENDS` text COMMENT 'Recp Tax Rends',
    `N_INCR_LOANS_CB` decimal(20,4) COMMENT 'N Incr Loans Cb',
    `N_INCR_CLT_LOAN_ADV` decimal(20,4) COMMENT 'N Incr Clt Loan Adv',
    `C_PAY_DIST_DPCP_INT_EXP` decimal(20,4) COMMENT 'C Pay Dist Dpcp Int Exp',
    `LT_AMORT_DEFERRED_EXP` text COMMENT 'Lt Amort Deferred Exp',
    `INVEST_LOSS` text COMMENT 'Invest Loss',
    `DECR_OPER_PAYABLE` text COMMENT 'Decr Oper Payable',
    `CONV_DEBT_INTO_CAP` text COMMENT 'Conv Debt Into Cap',
    `ANN_DATE` text COMMENT 'Ann Date',
    `C_PAID_GOODS_S` text COMMENT 'C Paid Goods S',
    `ST_CASH_OUT_ACT` decimal(20,4) COMMENT 'St Cash Out Act',
    `N_CASHFLOW_ACT` decimal(20,4) COMMENT 'N Cashflow Act',
    `N_CASHFLOW_INV_ACT` decimal(20,4) COMMENT 'N Cashflow Inv Act',
    `FREE_CASHFLOW` text COMMENT 'Free Cashflow',
    `C_CASH_EQU_BEG_PERIOD` decimal(20,4) COMMENT 'C Cash Equ Beg Period',
    `NET_DISM_CAPITAL_ADD` text COMMENT 'Net Dism Capital Add',
    `F_ANN_DATE` text COMMENT 'F Ann Date',
    `REPORT_TYPE` text COMMENT 'Report Type',
    `PREM_FR_ORIG_CONTR` text COMMENT 'Prem Fr Orig Contr',
    `IFC_CASH_INCR` decimal(20,4) COMMENT 'Ifc Cash Incr',
    `OTH_CASH_PAY_OPER_ACT` decimal(20,4) COMMENT 'Oth Cash Pay Oper Act',
    `IM_NET_CASHFLOW_OPER_ACT` text COMMENT 'Im Net Cashflow Oper Act',
    `BEG_BAL_CASH` text COMMENT 'Beg Bal Cash',
    `END_BAL_CASH_EQU` text COMMENT 'End Bal Cash Equ',
    `ID` bigint(20) COMMENT 'Id',
    `END_DATE` text COMMENT 'End Date',
    `N_INCR_DISP_TFA` text COMMENT 'N Incr Disp Tfa',
    `OTH_PAY_RAL_INV_ACT` text COMMENT 'Oth Pay Ral Inv Act',
    `STOT_OUT_INV_ACT` decimal(20,4) COMMENT 'Stot Out Inv Act',
    `OTH_CASH_RECP_RAL_FNC_ACT` text COMMENT 'Oth Cash Recp Ral Fnc Act',
    `LOSS_DISP_FIOLTA` text COMMENT 'Loss Disp Fiolta',
    `INCR_OPER_PAYABLE` text COMMENT 'Incr Oper Payable',
    `NET_PROFIT` text COMMENT 'Net Profit',
    `C_FR_OTH_OPERATE_A` decimal(20,4) COMMENT 'C Fr Oth Operate A(比率)',
    `C_PAY_CLAIMS_ORIG_INCO` text COMMENT 'C Pay Claims Orig Inco',
    `STOT_CASHOUT_FNC_ACT` decimal(20,4) COMMENT 'Stot Cashout Fnc Act',
    `FA_FNC_LEASES` text COMMENT 'Fa Fnc Leases',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `INCR_DEF_INC_TAX_LIAB` text COMMENT 'Incr Def Inc Tax Liab',
    `DECR_INVENTORIES` text COMMENT 'Decr Inventories',
    `CONV_COPBONDS_DUE_WITHIN_1Y` text COMMENT 'Conv Copbonds Due Within 1Y',
    `IM_N_INCR_CASH_EQU` text COMMENT 'Im N Incr Cash Equ',
    `USE_RIGHT_ASSET_DEP` text COMMENT 'Use Right Asset Dep',
    `N_INCR_CASH_CASH_EQU` decimal(20,4) COMMENT 'N Incr Cash Cash Equ',
    `DECR_DEF_INC_TAX_ASSETS` text COMMENT 'Decr Def Inc Tax Assets',
    `OTH_LOSS_ASSET` text COMMENT 'Oth Loss Asset',
    `IS_CALC` bigint(20) COMMENT 'Is Calc',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `FINAN_EXP` text COMMENT 'Finan Exp',
    `N_INCR_INSURED_DEP` text COMMENT 'N Incr Insured Dep',
    `N_INCR_DEP_CBOB` text COMMENT 'N Incr Dep Cbob',
    `C_DISP_WITHDRWL_INVEST` decimal(20,4) COMMENT 'C Disp Withdrwl Invest',
    `C_PAY_ACQ_CONST_FIOLTA` decimal(20,4) COMMENT 'C Pay Acq Const Fiolta',
    `END_BAL_CASH` text COMMENT 'End Bal Cash',
    `NET_CASH_RECE_SEC` text COMMENT 'Net Cash Rece Sec',
    `SYMBOL_FLAG` text COMMENT 'Symbol Flag',
    `N_INC_BORR_OTH_FI` text COMMENT 'N Inc Borr Oth Fi',
    `C_INF_FR_OPERATE_A` decimal(20,4) COMMENT 'C Inf Fr Operate A(比率)',
    `N_RECP_DISP_SOBU` text COMMENT 'N Recp Disp Sobu',
    `INCL_DVD_PROFIT_PAID_SC_MS` text COMMENT 'Incl Dvd Profit Paid Sc Ms',
    `DECR_DEFERRED_EXP` text COMMENT 'Decr Deferred Exp',
    `LOSS_FV_CHG` text COMMENT 'Loss Fv Chg',
    `CREATE_BY` text COMMENT 'Create By',
    `N_DEPOS_INCR_FI` decimal(20,4) COMMENT 'N Depos Incr Fi',
    `PAY_HANDLING_CHRG` decimal(20,4) COMMENT 'Pay Handling Chrg',
    `PAY_COMM_INSUR_PLCY` text COMMENT 'Pay Comm Insur Plcy',
    `N_CASH_FLOWS_FNC_ACT` decimal(20,4) COMMENT 'N Cash Flows Fnc Act',
    `PROV_DEPR_ASSETS` text COMMENT 'Prov Depr Assets',
    `AMORT_INTANG_ASSETS` text COMMENT 'Amort Intang Assets',
    `OTHERS` text COMMENT 'Others',
    `CREATE_TIME` text COMMENT 'Create Time',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `C_PAID_FOR_TAXES` decimal(20,4) COMMENT 'C Paid For Taxes',
    `STOT_INFLOWS_INV_ACT` decimal(20,4) COMMENT 'Stot Inflows Inv Act',
    `C_PAID_INVEST` decimal(20,4) COMMENT 'C Paid Invest',
    `PROC_ISSUE_BONDS` text COMMENT 'Proc Issue Bonds',
    `OTH_CASHPAY_RAL_FNC_ACT` decimal(20,4) COMMENT 'Oth Cashpay Ral Fnc Act',
    `C_CASH_EQU_END_PERIOD` decimal(20,4) COMMENT 'C Cash Equ End Period',
    `INCR_ACC_EXP` text COMMENT 'Incr Acc Exp',
    `N_INCR_LOANS_OTH_BANK` decimal(20,4) COMMENT 'N Incr Loans Oth Bank',
    `C_PAID_TO_FOR_EMPL` decimal(20,4) COMMENT 'C Paid To For Empl',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='现金流量表';



-- 业绩预告
CREATE TABLE IF NOT EXISTS aistockzml_tushare_forecast (
    `P_CHANGE_MIN` decimal(20,4) COMMENT 'P Change Min',
    `NOTICE_TIMES` bigint(20) COMMENT 'Notice Times',
    `SUMMARY` text COMMENT 'Summary',
    `CREATE_TIME` text COMMENT 'Create Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `ANN_DATE` text COMMENT 'Ann Date',
    `TYPE` text COMMENT 'Type',
    `P_CHANGE_MAX` decimal(20,4) COMMENT 'P Change Max',
    `FIRST_ANN_DATE` text COMMENT 'First Ann Date',
    `CHANGE_REASON` text COMMENT 'Change Reason',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `ID` bigint(20) COMMENT 'Id',
    `NET_PROFIT_MAX` decimal(20,4) COMMENT 'Net Profit Max',
    `LAST_PARENT_NET` decimal(20,4) COMMENT 'Last Parent Net',
    `CREATE_BY` text COMMENT 'Create By',
    `NET_PROFIT_MIN` decimal(20,4) COMMENT 'Net Profit Min',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `END_DATE` text COMMENT 'End Date',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业绩预告';



-- 业绩快报
CREATE TABLE IF NOT EXISTS aistockzml_tushare_express (
    `TOTAL_HLDR_EQY_EXC_MIN_INT` decimal(20,4) COMMENT 'Total Hldr Eqy Exc Min Int',
    `YOY_EPS` text COMMENT 'Yoy Eps',
    `GROWTH_BPS` text COMMENT 'Growth Bps',
    `OPEN_BPS` text COMMENT 'Open Bps',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `TOTAL_ASSETS` decimal(20,4) COMMENT 'Total Assets',
    `YOY_NET_PROFIT` decimal(20,4) COMMENT 'Yoy Net Profit',
    `YOY_EQUITY` text COMMENT 'Yoy Equity',
    `EPS_LAST_YEAR` text COMMENT 'Eps Last Year',
    `ID` bigint(20) COMMENT 'Id',
    `BPS` text COMMENT 'Bps',
    `YOY_TP` text COMMENT 'Yoy Tp',
    `END_DATE` text COMMENT 'End Date',
    `N_INCOME` decimal(20,4) COMMENT 'N Income',
    `YOY_OP` text COMMENT 'Yoy Op',
    `TP_LAST_YEAR` text COMMENT 'Tp Last Year',
    `CREATE_BY` text COMMENT 'Create By',
    `OPERATE_PROFIT` decimal(20,4) COMMENT 'Operate Profit(比率)',
    `YOY_SALES` text COMMENT 'Yoy Sales',
    `YOY_DEDU_NP` text COMMENT 'Yoy Dedu Np',
    `OP_LAST_YEAR` text COMMENT 'Op Last Year',
    `NP_LAST_YEAR` text COMMENT 'Np Last Year',
    `IS_AUDIT` bigint(20) COMMENT 'Is Audit',
    `REMARK` text COMMENT 'Remark',
    `UPDATE_BY` text COMMENT 'Update By',
    `TOTAL_PROFIT` decimal(20,4) COMMENT 'Total Profit',
    `DILUTED_EPS` decimal(20,4) COMMENT 'Diluted Eps',
    `DILUTED_ROE` decimal(20,4) COMMENT 'Diluted Roe',
    `OR_LAST_YEAR` text COMMENT 'Or Last Year',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `REVENUE` decimal(20,4) COMMENT 'Revenue',
    `YOY_ROE` text COMMENT 'Yoy Roe',
    `GROWTH_ASSETS` text COMMENT 'Growth Assets',
    `OPEN_NET_ASSETS` text COMMENT 'Open Net Assets',
    `PERF_SUMMARY` text COMMENT 'Perf Summary',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `CREATE_TIME` text COMMENT 'Create Time',
    `ANN_DATE` text COMMENT 'Ann Date',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业绩快报';



-- 分红送股
CREATE TABLE IF NOT EXISTS aistockzml_tushare_dividend (
    `ID` bigint(20) COMMENT 'Id',
    `END_DATE` text COMMENT 'End Date',
    `STK_DIV` decimal(20,4) COMMENT 'Stk Div',
    `STK_BO_RATE` text COMMENT 'Stk Bo Rate(比率)',
    `STK_CO_RATE` text COMMENT 'Stk Co Rate(比率)',
    `BASE_DATE` text COMMENT 'Base Date',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `PRE_ANN_DATE` text COMMENT 'Pre Ann Date',
    `CASH_DIV_TAX` decimal(20,4) COMMENT 'Cash Div Tax',
    `EX_DATE` text COMMENT 'Ex Date',
    `DIV_LISTDATE` text COMMENT 'Div Listdate',
    `IMP_ANN_DATE` text COMMENT 'Imp Ann Date',
    `IF_CHANGE` text COMMENT 'If Change',
    `CREATE_TIME` text COMMENT 'Create Time',
    `ANN_DATE` text COMMENT 'Ann Date',
    `DIV_PROC` text COMMENT 'Div Proc',
    `CASH_DIV` decimal(20,4) COMMENT 'Cash Div',
    `RECORD_DATE` text COMMENT 'Record Date',
    `CREATE_BY` text COMMENT 'Create By',
    `PAY_DATE` text COMMENT 'Pay Date',
    `BASE_SHARE` decimal(20,4) COMMENT 'Base Share',
    `UPDATE_BY` text COMMENT 'Update By',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分红送股';



-- 财务指标数据
CREATE TABLE IF NOT EXISTS aistockzml_tushare_fina_indicator (
    `CASH_RATIO` text COMMENT 'Cash Ratio',
    `NETDEBT` text COMMENT 'Netdebt',
    `FCFE_PS` text COMMENT 'Fcfe Ps',
    `TAX_TO_EBT` decimal(20,4) COMMENT 'Tax To Ebt',
    `PROFIT_PREFIN_EXP` text COMMENT 'Profit Prefin Exp',
    `Q_SALES_QOQ` decimal(20,4) COMMENT 'Q Sales Qoq',
    `UNDIST_PROFIT_PS` decimal(20,4) COMMENT 'Undist Profit Ps',
    `CURRENT_RATIO` text COMMENT 'Current Ratio',
    `CASH_TO_LIQDEBT` text COMMENT 'Cash To Liqdebt',
    `Q_SALEEXP_TO_GR` text COMMENT 'Q Saleexp To Gr',
    `Q_NETPROFIT_QOQ` decimal(20,4) COMMENT 'Q Netprofit Qoq',
    `RD_EXP` text COMMENT 'Rd Exp',
    `OCFPS` decimal(20,4) COMMENT 'Ocfps',
    `NPTA` decimal(20,4) COMMENT 'Npta',
    `OCF_TO_SHORTDEBT` text COMMENT 'Ocf To Shortdebt',
    `OP_TO_DEBT` decimal(20,4) COMMENT 'Op To Debt',
    `CFPS_YOY` decimal(20,4) COMMENT 'Cfps Yoy',
    `OR_YOY` decimal(20,4) COMMENT 'Or Yoy',
    `CAPITAL_RESE_PS` decimal(20,4) COMMENT 'Capital Rese Ps',
    `OP_INCOME` decimal(20,4) COMMENT 'Op Income',
    `INT_TO_TALCAP` text COMMENT 'Int To Talcap',
    `TANGASSET_TO_INTDEBT` text COMMENT 'Tangasset To Intdebt',
    `NOP_TO_EBT` decimal(20,4) COMMENT 'Nop To Ebt',
    `Q_DTPROFIT_TO_PROFIT` decimal(20,4) COMMENT 'Q Dtprofit To Profit',
    `DT_EPS_YOY` decimal(20,4) COMMENT 'Dt Eps Yoy',
    `NETPROFIT_YOY` decimal(20,4) COMMENT 'Netprofit Yoy',
    `FCFF` text COMMENT 'Fcff',
    `EQT_TO_TALCAPITAL` text COMMENT 'Eqt To Talcapital',
    `EXPENSE_OF_SALES` text COMMENT 'Expense Of Sales',
    `ROA_DP` decimal(20,4) COMMENT 'Roa Dp',
    `TOTAL_FA_TRUN` decimal(20,4) COMMENT 'Total Fa Trun',
    `Q_ADMINEXP_TO_GR` decimal(20,4) COMMENT 'Q Adminexp To Gr',
    `Q_GR_QOQ` decimal(20,4) COMMENT 'Q Gr Qoq',
    `UPDATE_BY` text COMMENT 'Update By',
    `DT_EPS` decimal(20,4) COMMENT 'Dt Eps',
    `CA_TURN` text COMMENT 'Ca Turn',
    `CASH_TO_LIQDEBT_WITHINTEREST` text COMMENT 'Cash To Liqdebt Withinterest',
    `Q_NETPROFIT_MARGIN` decimal(20,4) COMMENT 'Q Netprofit Margin',
    `BASIC_EPS_YOY` decimal(20,4) COMMENT 'Basic Eps Yoy',
    `Q_PROFIT_QOQ` decimal(20,4) COMMENT 'Q Profit Qoq',
    `Q_NETPROFIT_YOY` decimal(20,4) COMMENT 'Q Netprofit Yoy',
    `IMPAI_TTM` text COMMENT 'Impai Ttm',
    `TR_YOY` decimal(20,4) COMMENT 'Tr Yoy',
    `SYMBOL_FLAG` text COMMENT 'Symbol Flag',
    `INV_TURN` text COMMENT 'Inv Turn',
    `DAA` text COMMENT 'Daa',
    `TANGIBLE_ASSET` text COMMENT 'Tangible Asset',
    `EBIT_OF_GR` text COMMENT 'Ebit Of Gr',
    `OCF_TO_OPINCOME` decimal(20,4) COMMENT 'Ocf To Opincome',
    `OCF_TO_NETDEBT` text COMMENT 'Ocf To Netdebt',
    `Q_OPINCOME_TO_EBT` decimal(20,4) COMMENT 'Q Opincome To Ebt',
    `EXTRA_ITEM` decimal(20,4) COMMENT 'Extra Item',
    `ARTURN_DAYS` text COMMENT 'Arturn Days',
    `FA_TURN` text COMMENT 'Fa Turn',
    `NETWORKING_CAPITAL` text COMMENT 'Networking Capital',
    `Q_IMPAIR_TO_GR_TTM` text COMMENT 'Q Impair To Gr Ttm',
    `EQT_YOY` decimal(20,4) COMMENT 'Eqt Yoy',
    `Q_SALES_YOY` decimal(20,4) COMMENT 'Q Sales Yoy',
    `WORKING_CAPITAL` text COMMENT 'Working Capital',
    `ADMINEXP_OF_GR` decimal(20,4) COMMENT 'Adminexp Of Gr',
    `ROE` decimal(20,4) COMMENT 'Roe',
    `SALESCASH_TO_OR` text COMMENT 'Salescash To Or',
    `PROFIT_TO_OP` decimal(20,4) COMMENT 'Profit To Op',
    `Q_GSPROFIT_MARGIN` text COMMENT 'Q Gsprofit Margin',
    `EBT_YOY` decimal(20,4) COMMENT 'Ebt Yoy',
    `TOTAL_REVENUE_PS` decimal(20,4) COMMENT 'Total Revenue Ps',
    `CFPS` decimal(20,4) COMMENT 'Cfps',
    `ROIC` text COMMENT 'Roic',
    `TBASSETS_TO_TOTALASSETS` text COMMENT 'Tbassets To Totalassets',
    `Q_EPS` decimal(20,4) COMMENT 'Q Eps',
    `FCFE` text COMMENT 'Fcfe',
    `GROSSPROFIT_MARGIN` text COMMENT 'Grossprofit Margin',
    `OP_OF_GR` decimal(20,4) COMMENT 'Op Of Gr',
    `N_OP_PROFIT_OF_EBT` decimal(20,4) COMMENT 'N Op Profit Of Ebt',
    `OCF_TO_INTERESTDEBT` text COMMENT 'Ocf To Interestdebt',
    `QUICK_RATIO` text COMMENT 'Quick Ratio',
    `INTERESTDEBT` text COMMENT 'Interestdebt',
    `DILUTED2_EPS` decimal(20,4) COMMENT 'Diluted2 Eps',
    `BPS` decimal(20,4) COMMENT 'Bps',
    `RETAINEDPS` decimal(20,4) COMMENT 'Retainedps',
    `COGS_OF_SALES` text COMMENT 'Cogs Of Sales',
    `DEBT_TO_ASSETS` decimal(20,4) COMMENT 'Debt To Assets',
    `ASSETS_TO_EQT` decimal(20,4) COMMENT 'Assets To Eqt',
    `FINAEXP_OF_GR` text COMMENT 'Finaexp Of Gr',
    `NCA_TO_ASSETS` text COMMENT 'Nca To Assets',
    `OCF_TO_PROFIT` decimal(20,4) COMMENT 'Ocf To Profit',
    `OP_TO_LIQDEBT` text COMMENT 'Op To Liqdebt',
    `ROIC_YEARLY` text COMMENT 'Roic Yearly',
    `Q_INVESTINCOME` decimal(20,4) COMMENT 'Q Investincome',
    `Q_PROFIT_TO_GR` decimal(20,4) COMMENT 'Q Profit To Gr',
    `DT_NETPROFIT_YOY` decimal(20,4) COMMENT 'Dt Netprofit Yoy',
    `ROA` text COMMENT 'Roa',
    `ROA_YEARLY` decimal(20,4) COMMENT 'Roa Yearly',
    `Q_GC_TO_GR` text COMMENT 'Q Gc To Gr',
    `ANN_DATE` text COMMENT 'Ann Date',
    `INVEST_CAPITAL` text COMMENT 'Invest Capital',
    `EBIT_PS` text COMMENT 'Ebit Ps',
    `ROE_YOY` decimal(20,4) COMMENT 'Roe Yoy',
    `EBITDA` text COMMENT 'Ebitda',
    `INVESTINCOME_OF_EBT` decimal(20,4) COMMENT 'Investincome Of Ebt',
    `CURRENTDEBT_TO_DEBT` text COMMENT 'Currentdebt To Debt',
    `Q_FINAEXP_TO_GR` text COMMENT 'Q Finaexp To Gr',
    `Q_ROE` decimal(20,4) COMMENT 'Q Roe',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `EPS` decimal(20,4) COMMENT 'Eps',
    `GROSS_MARGIN` text COMMENT 'Gross Margin',
    `NONCURRENT_EXINT` text COMMENT 'Noncurrent Exint',
    `ROE_WAA` decimal(20,4) COMMENT 'Roe Waa',
    `ROA2_YEARLY` text COMMENT 'Roa2 Yearly',
    `OPINCOME_OF_EBT` decimal(20,4) COMMENT 'Opincome Of Ebt',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `INTERST_INCOME` text COMMENT 'Interst Income',
    `RETAINED_EARNINGS` decimal(20,4) COMMENT 'Retained Earnings',
    `DEBT_TO_EQT` decimal(20,4) COMMENT 'Debt To Eqt',
    `CREATE_BY` text COMMENT 'Create By',
    `EBIT` text COMMENT 'Ebit',
    `ROE_AVG` decimal(20,4) COMMENT 'Roe Avg',
    `DP_ASSETS_TO_EQT` decimal(20,4) COMMENT 'Dp Assets To Eqt',
    `BPS_YOY` decimal(20,4) COMMENT 'Bps Yoy',
    `Q_PROFIT_YOY` decimal(20,4) COMMENT 'Q Profit Yoy',
    `VALUECHANGE_INCOME` decimal(20,4) COMMENT 'Valuechange Income',
    `CURRENT_EXINT` text COMMENT 'Current Exint',
    `EQT_TO_DEBT` decimal(20,4) COMMENT 'Eqt To Debt',
    `Q_GR_YOY` decimal(20,4) COMMENT 'Q Gr Yoy',
    `EQUITY_YOY` decimal(20,4) COMMENT 'Equity Yoy',
    `ROE_DT` decimal(20,4) COMMENT 'Roe Dt',
    `DTPROFIT_TO_PROFIT` decimal(20,4) COMMENT 'Dtprofit To Profit',
    `CAPITALIZED_TO_DA` text COMMENT 'Capitalized To Da',
    `CA_TO_ASSETS` text COMMENT 'Ca To Assets',
    `EQT_TO_INTERESTDEBT` text COMMENT 'Eqt To Interestdebt',
    `TANGIBLEASSET_TO_DEBT` text COMMENT 'Tangibleasset To Debt',
    `OCF_TO_DEBT` decimal(20,4) COMMENT 'Ocf To Debt',
    `LONGDEBT_TO_WORKINGCAPITAL` text COMMENT 'Longdebt To Workingcapital',
    `LONGDEB_TO_DEBT` text COMMENT 'Longdeb To Debt',
    `NON_OP_PROFIT` decimal(20,4) COMMENT 'Non Op Profit',
    `Q_OP_YOY` decimal(20,4) COMMENT 'Q Op Yoy',
    `PROFIT_DEDT` decimal(20,4) COMMENT 'Profit Dedt',
    `AR_TURN` text COMMENT 'Ar Turn',
    `TANGIBLEASSET_TO_NETDEBT` text COMMENT 'Tangibleasset To Netdebt',
    `Q_EXP_TO_SALES` text COMMENT 'Q Exp To Sales',
    `OP_YOY` decimal(20,4) COMMENT 'Op Yoy',
    `Q_OP_QOQ` decimal(20,4) COMMENT 'Q Op Qoq',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `OP_TO_EBT` decimal(20,4) COMMENT 'Op To Ebt',
    `Q_OPINCOME` decimal(20,4) COMMENT 'Q Opincome',
    `Q_OCF_TO_SALES` decimal(20,4) COMMENT 'Q Ocf To Sales',
    `OCF_YOY` decimal(20,4) COMMENT 'Ocf Yoy',
    `ASSETS_YOY` decimal(20,4) COMMENT 'Assets Yoy',
    `SURPLUS_RESE_PS` decimal(20,4) COMMENT 'Surplus Rese Ps',
    `GC_OF_GR` text COMMENT 'Gc Of Gr',
    `ROE_YEARLY` decimal(20,4) COMMENT 'Roe Yearly',
    `OCF_TO_OR` decimal(20,4) COMMENT 'Ocf To Or',
    `EBITDA_TO_DEBT` text COMMENT 'Ebitda To Debt',
    `Q_DT_ROE` decimal(20,4) COMMENT 'Q Dt Roe',
    `Q_INVESTINCOME_TO_EBT` decimal(20,4) COMMENT 'Q Investincome To Ebt',
    `END_DATE` text COMMENT 'End Date',
    `REVENUE_PS` decimal(20,4) COMMENT 'Revenue Ps',
    `INVTURN_DAYS` text COMMENT 'Invturn Days',
    `ASSETS_TURN` decimal(20,4) COMMENT 'Assets Turn',
    `FCFF_PS` text COMMENT 'Fcff Ps',
    `EBIT_TO_INTEREST` text COMMENT 'Ebit To Interest',
    `TURN_DAYS` text COMMENT 'Turn Days',
    `Q_OP_TO_GR` decimal(20,4) COMMENT 'Q Op To Gr',
    `NETPROFIT_MARGIN` decimal(20,4) COMMENT 'Netprofit Margin',
    `SALEEXP_TO_GR` text COMMENT 'Saleexp To Gr',
    `FIXED_ASSETS` decimal(20,4) COMMENT 'Fixed Assets',
    `Q_DTPROFIT` decimal(20,4) COMMENT 'Q Dtprofit',
    `Q_NPTA` decimal(20,4) COMMENT 'Q Npta',
    `Q_SALESCASH_TO_OR` text COMMENT 'Q Salescash To Or',
    `Q_OCF_TO_OR` decimal(20,4) COMMENT 'Q Ocf To Or',
    `ID` bigint(20) COMMENT 'Id',
    `PROFIT_TO_GR` decimal(20,4) COMMENT 'Profit To Gr',
    `CREATE_TIME` text COMMENT 'Create Time',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务指标数据';



-- 主营业务构成
CREATE TABLE IF NOT EXISTS aistockzml_tushare_fina_mainbz (
    `UPDATE_TIME` text COMMENT 'Update Time',
    `END_DATE` text COMMENT 'End Date',
    `BZ_PROFIT` text COMMENT 'Bz Profit',
    `BZ_PROFIT_YOY` decimal(20,4) COMMENT 'Bz Profit Yoy',
    `CURR_TYPE` text COMMENT 'Curr Type',
    `BZ_SALES` decimal(20,4) COMMENT 'Bz Sales',
    `BZ_COST` text COMMENT 'Bz Cost',
    `BZ_SALES_PCT` decimal(20,4) COMMENT 'Bz Sales Pct(比率)',
    `BZ_COST_PCT` decimal(20,4) COMMENT 'Bz Cost Pct(比率)',
    `IS_PUBLISHED` text COMMENT 'Is Published',
    `CREATE_TIME` text COMMENT 'Create Time',
    `CREATE_BY` text COMMENT 'Create By',
    `ID` bigint(20) COMMENT 'Id',
    `BZ_CODE` text COMMENT 'Bz Code代码',
    `BZ_PROFIT_PCT` decimal(20,4) COMMENT 'Bz Profit Pct(比率)',
    `BZ_SALES_YOY` decimal(20,4) COMMENT 'Bz Sales Yoy',
    `BZ_MARGIN_YOY` decimal(20,4) COMMENT 'Bz Margin Yoy',
    `UPDATE_BY` text COMMENT 'Update By',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `BZ_ITEM` text COMMENT 'Bz Item',
    `BZ_COST_YOY` decimal(20,4) COMMENT 'Bz Cost Yoy',
    `BZ_MARGIN_GROSS` decimal(20,4) COMMENT 'Bz Margin Gross',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `SYMBOL_FLAG` text COMMENT 'Symbol Flag',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='主营业务构成';



-- 财报披露日期表
CREATE TABLE IF NOT EXISTS aistockzml_tushare_disclosure_date (
    `TS_CODE` text COMMENT 'Ts Code代码',
    `PRE_DATE` text COMMENT 'Pre Date',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `ID` bigint(20) COMMENT 'Id',
    `ANN_DATE` text COMMENT 'Ann Date',
    `END_DATE` text COMMENT 'End Date',
    `ACTUAL_DATE` text COMMENT 'Actual Date',
    `MODIFY_DATE` text COMMENT 'Modify Date',
    `CREATE_TIME` text COMMENT 'Create Time',
    `CREATE_BY` text COMMENT 'Create By',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财报披露日期表';



-- 日线行情-未复权行情
CREATE TABLE IF NOT EXISTS aistockzml_tushare_daily (
    `LOW` decimal(20,4) COMMENT 'Low',
    `PRE_CLOSE` decimal(20,4) COMMENT 'Pre Close',
    `PCT_CHANGE` decimal(20,4) COMMENT 'Pct Change(比率)',
    `HIGH` decimal(20,4) COMMENT 'High',
    `CHANGE` decimal(20,4) COMMENT 'Change',
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `CREATE_TIME` text COMMENT 'Create Time',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `ID` bigint(20) COMMENT 'Id',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `UPDATE_BY` text COMMENT 'Update By',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `CLOSE` decimal(20,4) COMMENT 'Close',
    `OPEN` decimal(20,4) COMMENT 'Open',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `CREATE_BY` text COMMENT 'Create By',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='日线行情-未复权行情';



-- 周线行情-历史-未复权行情
CREATE TABLE IF NOT EXISTS aistockzml_tushare_weekly (
    `ID` bigint(20) COMMENT 'Id',
    `OPEN` decimal(20,4) COMMENT 'Open',
    `LOW` decimal(20,4) COMMENT 'Low',
    `CLOSE` decimal(20,4) COMMENT 'Close',
    `PCT_CHANGE` decimal(20,4) COMMENT 'Pct Change(比率)',
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `CREATE_TIME` text COMMENT 'Create Time',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `HIGH` decimal(20,4) COMMENT 'High',
    `PRE_CLOSE` decimal(20,4) COMMENT 'Pre Close',
    `CHANGE` decimal(20,4) COMMENT 'Change',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='周线行情-历史-未复权行情';



-- 月线行情-历史-未复权行情
CREATE TABLE IF NOT EXISTS aistockzml_tushare_monthly (
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `UPDATE_BY` text COMMENT 'Update By',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `HIGH` decimal(20,4) COMMENT 'High',
    `CHANGE` decimal(20,4) COMMENT 'Change',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `CREATE_TIME` text COMMENT 'Create Time',
    `CREATE_BY` text COMMENT 'Create By',
    `OPEN` decimal(20,4) COMMENT 'Open',
    `LOW` decimal(20,4) COMMENT 'Low',
    `PRE_CLOSE` decimal(20,4) COMMENT 'Pre Close',
    `ID` bigint(20) COMMENT 'Id',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `CLOSE` decimal(20,4) COMMENT 'Close',
    `PCT_CHANGE` decimal(20,4) COMMENT 'Pct Change(比率)',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='月线行情-历史-未复权行情';



-- 周线行情-每日更新-未复权行情
CREATE TABLE IF NOT EXISTS aistockzml_tushare_weekly_336 (
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `OPEN` decimal(20,4) COMMENT 'Open',
    `HIGH` decimal(20,4) COMMENT 'High',
    `LOW` decimal(20,4) COMMENT 'Low',
    `PCT_CHANGE` decimal(20,4) COMMENT 'Pct Change(比率)',
    `UPDATE_BY` text COMMENT 'Update By',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `CREATE_TIME` text COMMENT 'Create Time',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `PRE_CLOSE` decimal(20,4) COMMENT 'Pre Close',
    `CHANGE` decimal(20,4) COMMENT 'Change',
    `CREATE_BY` text COMMENT 'Create By',
    `ID` bigint(20) COMMENT 'Id',
    `CLOSE` decimal(20,4) COMMENT 'Close',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='周线行情-每日更新-未复权行情';



-- 月线行情-每日更新-未复权行情
CREATE TABLE IF NOT EXISTS aistockzml_tushare_monthly_336 (
    `TS_CODE` text COMMENT 'Ts Code代码',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `PRE_CLOSE` decimal(20,4) COMMENT 'Pre Close',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `ID` bigint(20) COMMENT 'Id',
    `CLOSE` decimal(20,4) COMMENT 'Close',
    `PCT_CHANGE` decimal(20,4) COMMENT 'Pct Change(比率)',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `OPEN` decimal(20,4) COMMENT 'Open',
    `HIGH` decimal(20,4) COMMENT 'High',
    `LOW` decimal(20,4) COMMENT 'Low',
    `CHANGE` decimal(20,4) COMMENT 'Change',
    `CREATE_TIME` text COMMENT 'Create Time',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='月线行情-每日更新-未复权行情';



-- 周线行情-每日更新-复权行情
CREATE TABLE IF NOT EXISTS aistockzml_tushare_weekly_365 (
    `CHANGE` decimal(20,4) COMMENT 'Change',
    `CREATE_TIME` text COMMENT 'Create Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `CLOSE` decimal(20,4) COMMENT 'Close',
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `ID` bigint(20) COMMENT 'Id',
    `HIGH` decimal(20,4) COMMENT 'High',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `PRE_CLOSE` decimal(20,4) COMMENT 'Pre Close',
    `PCT_CHANGE` decimal(20,4) COMMENT 'Pct Change(比率)',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `OPEN` decimal(20,4) COMMENT 'Open',
    `LOW` decimal(20,4) COMMENT 'Low',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='周线行情-每日更新-复权行情';



-- 月线行情-每日更新-复权行情
CREATE TABLE IF NOT EXISTS aistockzml_tushare_monthly_365 (
    `TS_CODE` text COMMENT 'Ts Code代码',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `OPEN` decimal(20,4) COMMENT 'Open',
    `HIGH` decimal(20,4) COMMENT 'High',
    `PRE_CLOSE` decimal(20,4) COMMENT 'Pre Close',
    `PCT_CHANGE` decimal(20,4) COMMENT 'Pct Change(比率)',
    `CREATE_BY` text COMMENT 'Create By',
    `ID` bigint(20) COMMENT 'Id',
    `LOW` decimal(20,4) COMMENT 'Low',
    `CHANGE` decimal(20,4) COMMENT 'Change',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `CLOSE` decimal(20,4) COMMENT 'Close',
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `CREATE_TIME` text COMMENT 'Create Time',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='月线行情-每日更新-复权行情';



-- 股票每日基本面指标
CREATE TABLE IF NOT EXISTS aistockzml_tushare_daily_basic (
    `PE` decimal(20,4) COMMENT 'Pe',
    `PS` decimal(20,4) COMMENT 'Ps',
    `TOTAL_MV` decimal(20,4) COMMENT 'Total Mv',
    `CIRC_MV` decimal(20,4) COMMENT 'Circ Mv',
    `CREATE_TIME` text COMMENT 'Create Time',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `CLOSE` decimal(20,4) COMMENT 'Close',
    `VOLUME_RATIO` decimal(20,4) COMMENT 'Volume Ratio',
    `PB` decimal(20,4) COMMENT 'Pb',
    `DV_TTM` decimal(20,4) COMMENT 'Dv Ttm',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `TURNOVER_RATE` decimal(20,4) COMMENT 'Turnover Rate(比率)',
    `PE_TTM` decimal(20,4) COMMENT 'Pe Ttm',
    `PS_TTM` decimal(20,4) COMMENT 'Ps Ttm',
    `DV_RATIO` decimal(20,4) COMMENT 'Dv Ratio',
    `TOTAL_SHARE` decimal(20,4) COMMENT 'Total Share',
    `FREE_SHARE` decimal(20,4) COMMENT 'Free Share',
    `UDLIMIT_STATUS` bigint(20) COMMENT 'Udlimit Status',
    `ID` bigint(20) COMMENT 'Id',
    `TURNOVER_RATE_F` decimal(20,4) COMMENT 'Turnover Rate F(比率)',
    `FLOAT_SHARE` decimal(20,4) COMMENT 'Float Share',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票每日基本面指标';



-- 港股通每日成交统计
CREATE TABLE IF NOT EXISTS aistockzml_tushare_ggt_daily (
    `ID` bigint(20) COMMENT 'Id',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `MARKETTYPE` bigint(20) COMMENT 'Markettype',
    `BUY_AMOUNT` decimal(20,4) COMMENT 'Buy Amount(金额)',
    `BUY_VOLUME` decimal(20,4) COMMENT 'Buy Volume',
    `SELL_AMOUNT` decimal(20,4) COMMENT 'Sell Amount(金额)',
    `SELL_VOLUME` decimal(20,4) COMMENT 'Sell Volume',
    `CREATE_BY` text COMMENT 'Create By',
    `CREATE_TIME` text COMMENT 'Create Time',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='港股通每日成交统计';



-- 港股通每月成交统计
CREATE TABLE IF NOT EXISTS aistockzml_tushare_ggt_monthly (
    `UPDATE_TIME` text COMMENT 'Update Time',
    `ID` bigint(20) COMMENT 'Id',
    `DAY_SELL_VOL` decimal(20,4) COMMENT 'Day Sell Vol',
    `TOTAL_BUY_AMT` decimal(20,4) COMMENT 'Total Buy Amt(金额)',
    `TOTAL_SELL_AMT` decimal(20,4) COMMENT 'Total Sell Amt(金额)',
    `TOTAL_SELL_VOL` decimal(20,4) COMMENT 'Total Sell Vol',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `MONTH` text COMMENT 'Month',
    `DAY_BUY_AMT` decimal(20,4) COMMENT 'Day Buy Amt(金额)',
    `DAY_BUY_VOL` decimal(20,4) COMMENT 'Day Buy Vol',
    `DAY_SELL_AMT` decimal(20,4) COMMENT 'Day Sell Amt(金额)',
    `TOTAL_BUY_VOL` decimal(20,4) COMMENT 'Total Buy Vol',
    `CREATE_TIME` text COMMENT 'Create Time',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='港股通每月成交统计';



-- 股权质押统计数据
CREATE TABLE IF NOT EXISTS aistockzml_tushare_pledge_stat (
    `CREATE_TIME` text COMMENT 'Create Time',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `PLEDGE_COUNT` bigint(20) COMMENT 'Pledge Count(数量)',
    `REST_PLEDGE` decimal(20,4) COMMENT 'Rest Pledge',
    `PLEDGE_RATIO` decimal(20,4) COMMENT 'Pledge Ratio',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `ID` bigint(20) COMMENT 'Id',
    `END_DATE` text COMMENT 'End Date',
    `UNREST_PLEDGE` decimal(20,4) COMMENT 'Unrest Pledge',
    `TOTAL_SHARE` decimal(20,4) COMMENT 'Total Share',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股权质押统计数据';



-- 股权质押明细
CREATE TABLE IF NOT EXISTS aistockzml_tushare_pledge_detail (
    `PLEDGED_AMOUNT` decimal(20,4) COMMENT 'Pledged Amount(金额)',
    `IS_BUYBACK` text COMMENT 'Is Buyback',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `ID` bigint(20) COMMENT 'Id',
    `START_DATE` text COMMENT 'Start Date',
    `IS_RELEASE` text COMMENT 'Is Release',
    `P_TOTAL_RATIO` decimal(20,4) COMMENT 'P Total Ratio',
    `H_TOTAL_RATIO` decimal(20,4) COMMENT 'H Total Ratio',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `HOLDER_NAME` text COMMENT 'Holder Name名称',
    `END_DATE` text COMMENT 'End Date',
    `RELEASE_DATE` text COMMENT 'Release Date',
    `CREATE_TIME` text COMMENT 'Create Time',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `ANN_DATE` text COMMENT 'Ann Date',
    `PLEDGOR` text COMMENT 'Pledgor',
    `HOLDING_AMOUNT` decimal(20,4) COMMENT 'Holding Amount(金额)',
    `DESC` text COMMENT 'Desc',
    `HOLDER_TYPE` text COMMENT 'Holder Type',
    `PLEDGE_AMOUNT` decimal(20,4) COMMENT 'Pledge Amount(金额)',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股权质押明细';



-- 股票回购
CREATE TABLE IF NOT EXISTS aistockzml_tushare_repurchase (
    `END_DATE` text COMMENT 'End Date',
    `CREATE_TIME` text COMMENT 'Create Time',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `ANN_DATE` text COMMENT 'Ann Date',
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `UPDATE_BY` text COMMENT 'Update By',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `EXP_DATE` text COMMENT 'Exp Date',
    `HIGH_LIMIT` decimal(20,4) COMMENT 'High Limit',
    `REPO_GOAL` text COMMENT 'Repo Goal',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `ID` bigint(20) COMMENT 'Id',
    `PROC` text COMMENT 'Proc',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `LOW_LIMIT` decimal(20,4) COMMENT 'Low Limit',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票回购';



-- 限售股解禁
CREATE TABLE IF NOT EXISTS aistockzml_tushare_share_float (
    `ID` bigint(20) COMMENT 'Id',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `ANN_DATE` text COMMENT 'Ann Date',
    `FLOAT_RATIO` decimal(20,4) COMMENT 'Float Ratio',
    `SHARE_TYPE` text COMMENT 'Share Type',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `CREATE_TIME` text COMMENT 'Create Time',
    `UPDATE_BY` text COMMENT 'Update By',
    `FLOAT_DATE` text COMMENT 'Float Date',
    `FLOAT_SHARE` decimal(20,4) COMMENT 'Float Share',
    `HOLDER_NAME` text COMMENT 'Holder Name名称',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='限售股解禁';



-- 大宗交易
CREATE TABLE IF NOT EXISTS aistockzml_tushare_block_trade (
    `PRICE` decimal(20,4) COMMENT 'Price',
    `BUYER` text COMMENT 'Buyer',
    `SELLER` text COMMENT 'Seller',
    `NUM_TIMES` bigint(20) COMMENT 'Num Times(数量)',
    `CREATE_TIME` text COMMENT 'Create Time',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `TRADE_DATE` text COMMENT 'Trade Date',
    `VOL` decimal(20,4) COMMENT 'Vol',
    `AMOUNT` decimal(20,4) COMMENT 'Amount(金额)',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `ID` bigint(20) COMMENT 'Id',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='大宗交易';



-- 股东人数
CREATE TABLE IF NOT EXISTS aistockzml_tushare_stk_holdernumber (
    `ID` bigint(20) COMMENT 'Id',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `HOLDER_NUM` bigint(20) COMMENT 'Holder Num(数量)',
    `HOLDER_TOTAL` bigint(20) COMMENT 'Holder Total',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `ANN_DATE` text COMMENT 'Ann Date',
    `END_DATE` text COMMENT 'End Date',
    `CREATE_TIME` text COMMENT 'Create Time',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股东人数';



-- 股东增减持
CREATE TABLE IF NOT EXISTS aistockzml_tushare_stk_holdertrade (
    `BEGIN_DATE` text COMMENT 'Begin Date',
    `HOLDER_NAME` text COMMENT 'Holder Name名称',
    `CHANGE_VOL` decimal(20,4) COMMENT 'Change Vol',
    `AFTER_RATIO` decimal(20,4) COMMENT 'After Ratio',
    `CLOSE_DATE` text COMMENT 'Close Date',
    `TOTAL_SHARE` decimal(20,4) COMMENT 'Total Share',
    `CREATE_TIME` text COMMENT 'Create Time',
    `CREATE_BY` text COMMENT 'Create By',
    `UPDATE_BY` text COMMENT 'Update By',
    `ID` bigint(20) COMMENT 'Id',
    `IN_DE` text COMMENT 'In De',
    `AFTER_SHARE` decimal(20,4) COMMENT 'After Share',
    `AVG_PRICE` decimal(20,4) COMMENT 'Avg Price',
    `UPDATE_FLAG` text COMMENT 'Update Flag',
    `UPDATE_TIME` text COMMENT 'Update Time',
    `TS_CODE` text COMMENT 'Ts Code代码',
    `ANN_DATE` text COMMENT 'Ann Date',
    `HOLDER_TYPE` text COMMENT 'Holder Type',
    `CHANGE_RATIO` decimal(20,4) COMMENT 'Change Ratio',
    `etl_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股东增减持';
