-- 接口名称：dividend
-- 分红送股数据
CREATE TABLE IF NOT EXISTS aistockzml_tushare_dividend (
    ID INT COMMENT '主键ID',
    TS_CODE VARCHAR(20) COMMENT 'TS代码',
    END_DATE VARCHAR(8) COMMENT '分红年度',
    ANN_DATE VARCHAR(8) COMMENT '预案公告日',
    PRE_ANN_DATE VARCHAR(8) COMMENT '预公告日期',
    DIV_PROC VARCHAR(20) COMMENT '实施进度',
    STK_DIV DECIMAL(20,4) COMMENT '每股送转',
    STK_BO_RATE DECIMAL(20,4) COMMENT '每股送股比例',
    STK_CO_RATE DECIMAL(20,4) COMMENT '每股转增比例',
    CASH_DIV DECIMAL(20,4) COMMENT '每股分红（税后）',
    CASH_DIV_TAX DECIMAL(20,4) COMMENT '每股分红（税前）',
    RECORD_DATE VARCHAR(8) COMMENT '股权登记日',
    EX_DATE VARCHAR(8) COMMENT '除权除息日',
    PAY_DATE VARCHAR(8) COMMENT '派息日',
    DIV_LISTDATE VARCHAR(8) COMMENT '红股上市日',
    IMP_ANN_DATE VARCHAR(8) COMMENT '实施公告日',
    BASE_DATE VARCHAR(8) COMMENT '基准日',
    BASE_SHARE DECIMAL(20,4) COMMENT '基准股本（万）',
    IF_CHANGE VARCHAR(10) COMMENT '是否变更',
    CREATE_BY VARCHAR(50) COMMENT '创建人',
    CREATE_TIME DATETIME COMMENT '创建时间',
    UPDATE_BY VARCHAR(50) COMMENT '更新人',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    etl_time DATETIME COMMENT '数据加载时间',
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分红送股数据';
