-- 接口名称：dc_index
-- 东方财富概念板块
CREATE TABLE IF NOT EXISTS aistockzml_tushare_dc_index (
    ID INT COMMENT '主键ID',
    TS_CODE VARCHAR(20) COMMENT '指数代码',
    CODE VARCHAR(20) COMMENT '板块代码',
    NAME VARCHAR(100) COMMENT '板块名称',
    TRADE_DATE VARCHAR(8) COMMENT '交易日期',
    CATEGORY VARCHAR(20) COMMENT '板块类型',
    CLOSE DECIMAL(20,4) COMMENT '收盘点位',
    `CHANGE` DECIMAL(20,4) COMMENT '涨跌点位',
    PCT_CHANGE DECIMAL(20,4) COMMENT '涨跌幅',
    LEAD_STOCK VARCHAR(100) COMMENT '领涨股票名称',
    LEAD_STOCK_CODE VARCHAR(20) COMMENT '领涨股票代码',
    LEAD_STOCK_PCT_CHANGE DECIMAL(20,4) COMMENT '领涨股票涨跌幅',
    TOTAL_MV DECIMAL(20,4) COMMENT '总市值（万元）',
    TURNOVER_RATE DECIMAL(20,4) COMMENT '换手率',
    RISE_NUM INT COMMENT '上涨家数',
    FALL_NUM INT COMMENT '下降家数',
    CREATE_BY VARCHAR(50) COMMENT '创建人',
    CREATE_TIME DATETIME COMMENT '创建时间',
    UPDATE_BY VARCHAR(50) COMMENT '更新人',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    INSERT_TIME VARCHAR(20) COMMENT '插入时间',
    etl_time DATETIME COMMENT '数据加载时间',
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='东方财富行业概念板块';
